# Generated by Django 3.0.6 on 2020-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200611_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.SmallIntegerField(choices=[(1, 'Organizacja pozarządowa'), (2, 'Zbiórka lokalna'), (0, 'Fundacja')], default=0),
        ),
    ]
